service: graphql-api-with-nodejs-mongodb-lambda
provider:
  name: aws
  runtime: nodejs20.x
functions:
  graphql-api:
    handler: dist/lambda.handler
    events:
      - http: ANY /
plugins:
  - serverless-dotenv-plugin
custom:
  dotenv:
    path: .env.production